language: r
sudo: required
cache: packages

r_github_packages:
  - yrosseel/lavaan

warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: bionic
      r: release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - jags
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - _R_CHECK_FORCE_SUGGESTS_=false
    - os: linux
      dist: bionic
      r: devel
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - jags
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - _R_CHECK_FORCE_SUGGESTS_=false


before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native" >> ~/.R/Makevars
  - echo "CXX14=g++-7 -std=c++1y -fPIC" >> ~/.R/Makevars
